export const runtimeRequestChannel = "deskto:runtime:request"
export const runtimeEventChannel = "deskto:runtime:event"
export const pickProjectChannel = "deskto:desktop:pick-project"
export const pickPackChannel = "deskto:desktop:pick-pack"
export const openExternalChannel = "deskto:desktop:open-external"
export const openFolderChannel = "deskto:desktop:open-folder"
