export const runtimeRequestChannel = "appto:runtime:request"
export const runtimeEventChannel = "appto:runtime:event"
export const pickProjectChannel = "appto:desktop:pick-project"
export const pickPackChannel = "appto:desktop:pick-pack"
export const openExternalChannel = "appto:desktop:open-external"
